export enum BuffStack {
  HABILIDADE = "Habilidade",
  PERICIA = "Perícia",
  ITEM = "Item",
  MAGIA = "Magia",
  PARCEIRO = "Parceiro",
  ARMADURA = "Armadura",
  ESCUDO = "Escudo",
  ATRIBUTO_CARISMA = "Atributo Carisma",
  ATRIBUTO_SABEDORIA = "Atributo Sabedoria",
  ATRIBUTO_INTELIGENCIA = "Atributo Inteligencia",
  ATRIBUTO_CONSTITUICAO = "Atributo Constituicao",
  ATRIBUTO_DESTREZA = "Atributo Destreza",
  ATRIBUTO_FORCA = "Atributo Forca",
}
