import { Fonte } from "../fonte/fonte";
import Biografia from "./model/Biografia";

export const biografias = [
  new Biografia(1, "Acólito", Fonte.BASICO),
  new Biografia(2, "Amigo dos Animais", Fonte.BASICO),
  new Biografia(3, "Amiésico", Fonte.BASICO),
  new Biografia(4, "Aristocrata", Fonte.BASICO),
  new Biografia(5, "Aristocrata", Fonte.BASICO),
  new Biografia(6, "Artesão", Fonte.BASICO),
  new Biografia(7, "Artista", Fonte.BASICO),
  new Biografia(8, "Assistente de Laboratório", Fonte.BASICO),
  new Biografia(9, "Batedor", Fonte.BASICO),
  new Biografia(10, "Capanga", Fonte.BASICO),
  new Biografia(11, "Charlatão", Fonte.BASICO),
  new Biografia(12, "Circense", Fonte.BASICO),
  new Biografia(13, "Criminoso", Fonte.BASICO),
  new Biografia(14, "Curandeiro", Fonte.BASICO),
  new Biografia(15, "Eremita", Fonte.BASICO),
  new Biografia(16, "Escravo", Fonte.BASICO),
  new Biografia(17, "Estudioso", Fonte.BASICO),
  new Biografia(18, "Fazendeiro", Fonte.BASICO),
  new Biografia(19, "Forasteiro", Fonte.BASICO),
  new Biografia(20, "Gladiador", Fonte.BASICO),
  new Biografia(21, "Guarda", Fonte.BASICO),
  new Biografia(22, "Herdeiro", Fonte.BASICO),
  new Biografia(23, "Herói Camponês", Fonte.BASICO),
  new Biografia(24, "Marujo", Fonte.BASICO),
  new Biografia(25, "Mateiro", Fonte.BASICO),
  new Biografia(26, "Membro de Guilda", Fonte.BASICO),
  new Biografia(27, "Mercador", Fonte.BASICO),
  new Biografia(28, "Minerador", Fonte.BASICO),
  new Biografia(29, "Nômade", Fonte.BASICO),
  new Biografia(30, "Pivete", Fonte.BASICO),
  new Biografia(31, "Refugiado", Fonte.BASICO),
  new Biografia(32, "Seguidor", Fonte.BASICO),
  new Biografia(33, "Selvagem", Fonte.BASICO),
  new Biografia(34, "Soldado", Fonte.BASICO),
  new Biografia(35, "Taverneiro", Fonte.BASICO),
  new Biografia(36, "Trabalhador", Fonte.BASICO),
];
