export enum PoderSelect {
  NENHUM = 0,
  HABILIDADE_ORIGEM_1 = 1,
  HABILIDADE_ORIGEM_2 = 2,
  ACTIVE_CHILD = 3,
  HABILIDADE_ORIGEM_1_SELECT = 4,
  HABILIDADE_ORIGEM_2_SELECT = 5,
  PERICIA_CLASSE = 6,
  PERICIA_FIXA_CLASSE = 7,
  PERICIA_INTELIGENCIA = 8,
}
