export enum Categoria {
  habilidadesHumano = "Humano",
  habilidadesAnao = "Anão",
  habilidadesDahllan = "Dahllan",
  habilidadesElfo = "Elfo",
  habilidadesGoblin = "Goblin",
  habilidadesLefou = "Lefou",
  habilidadesMinotauro = "Minotauro",
  habilidadesQareen = "Qareen",
  habilidadesGolem = "Golem",
  habilidadesHynne = "Hynne",
  habilidadesKliren = "Kliren",
  habilidadesMedusa = "Medusa",
  habilidadesSereiaTritao = "Sereia/Tritao",
  habilidadesSilfide = "Silfide",
  habilidadesSuraggel = "Suraggel",
  habilidadesAggelus = "Suraggel (Aggelus)",
  habilidadesSulfure = "Suraggel (Sulfure)",
  habilidadesTrog = "Trog",

  Magia = "Magia",
  Pericia = "Pericia",
  PoderGeral = "Poder Geral",
  PoderCombate = "Poder de Combate",
  PoderTormenta = "Poder da Tormenta",
  Outro = "Outro",
}
