export enum Categoria {
  habilidadesHumano = "Humano",
  habilidadesAnao = "Anão",
  habilidadesDahllan = "Dahllan",
  habilidadesElfo = "Elfo",
  habilidadesGoblin = "Goblin",
  habilidadesLefou = "Lefou",
  habilidadesMinotauro = "Minotauro",
  habilidadesQareen = "Qareen",
  habilidadesGolem = "Golem",
  habilidadesHynne = "Hynne",
  habilidadesKliren = "Kliren",
  habilidadesMedusa = "Medusa",
  habilidadesSereiaTritao = "Sereia/Tritao",
  habilidadesSilfide = "Silfide",
  habilidadesSuraggel = "Suraggel",
  habilidadesAggelus = "Suraggel (Aggelus)",
  habilidadesSulfure = "Suraggel (Sulfure)",
  habilidadesTrog = "Trog",

  habilidadesArcanista = "Arcanista",
  habilidadesBarbaro = "Barbaro",
  habilidadesBardo = "Bardo",
  habilidadesBucaneiro = "Bucaneiro",
  habilidadesCacador = "Caçador",
  habilidadesCavaleiro = "Cavaleiro",
  habilidadesClerigo = "Clérigo",
  habilidadesDruida = "Druida",
  habilidadesGuerreiro = "Guerreiro",
  habilidadesInventor = "Inventor",
  habilidadesLadino = "Ladino",
  habilidadesLutador = "Lutador",
  habilidadesNobre = "Nobre",
  habilidadesPaladino = "Paladino",

  Magia = "Magia",
  Pericia = "Pericia",
  PoderGeral = "Poder Geral",
  PoderCombate = "Poder de Combate",
  PoderDestino = "Poder de Destino",
  PoderMagia = "Poder de Magia",
  PoderTormenta = "Poder da Tormenta",
  PoderConcedido = "Poder Concedido",
  PoderClasse = "Poder de Classe",
  Outro = "Outro",
}
