import Pericia from "./model/Pericia";
import { modificadores } from "../modificadores";

export const pericias = [
  new Pericia(1, "Acrobacia", modificadores[1]),
  new Pericia(2, "Adestramento", modificadores[5]),
  new Pericia(3, "Atletismo", modificadores[0]),
  new Pericia(4, "Atuação", modificadores[5]),
  new Pericia(5, "Cavalgar", modificadores[1]),
  new Pericia(6, "Conhecimento", modificadores[3]),
  new Pericia(7, "Cura", modificadores[4]),
  new Pericia(8, "Diplomacia", modificadores[5]),
  new Pericia(9, "Enganação", modificadores[5]),
  new Pericia(10, "Fortitude", modificadores[2]),
  new Pericia(11, "Furtividade", modificadores[1]),
  new Pericia(12, "Guerra", modificadores[3]),
  new Pericia(13, "Iniciativa", modificadores[1]),
  new Pericia(14, "Intimidação", modificadores[5]),
  new Pericia(15, "Intuição", modificadores[4]),
  new Pericia(16, "Investigação", modificadores[3]),
  new Pericia(17, "Jogatina", modificadores[5]),
  new Pericia(18, "Ladinagem", modificadores[1]),
  new Pericia(19, "Luta", modificadores[0]),
  new Pericia(20, "Misticismo", modificadores[3]),
  new Pericia(21, "Nobreza", modificadores[3]),
  new Pericia(22, "Oficio", modificadores[3]),
  new Pericia(23, "Percepção", modificadores[4]),
  new Pericia(24, "Pilotagem", modificadores[1]),
  new Pericia(25, "Pontaria", modificadores[1]),
  new Pericia(26, "Reflexos", modificadores[1]),
  new Pericia(27, "Religião", modificadores[4]),
  new Pericia(28, "Sobrevivencia", modificadores[4]),
  new Pericia(29, "Vontade", modificadores[4]),
];
