import PatchNote from "./model/PatchNotes";

export const patches: PatchNote[] = [
  new PatchNote(7, "v0.7.7", [
    "Adicionadas habilidades de classe (Poderes ainda nao inclusos)",
    "Correções de detalhes menores (como destreza na defesa)",
  ]),
  new PatchNote(6, "v0.7.6", [
    "Treinamento de pericias por raca",
    "Treinamento de pericias por origem",
    "Treinamento de pericias fixas de classe",
    "Treinamento de pericias de classe",
    "Treinamento de pericias de inteligencia",
  ]),
  new PatchNote(5, "v0.7.5", [
    "A maioria das habilidades de raça foi implementada, no entanto, algumas ainda estão faltando. Essas habilidades serão adicionadas em futuras atualizações conforme o restante da ficha for desenvolvida. Abaixo estão algumas habilidades que ainda não foram implementadas. Qualquer habilidade não mencionada está funcional e habilitada, de acordo com meus testes. Caso encontre algum erro, por favor, informe-me no privado do Discord:",
    "Humano: Versátil => Lista de poderes gerais não implementada",
    "Anão: Conhecimento das Rochas => Bônus situacional não implementado",
    "Anão: Devagar e Sempre => Ignorar redução de armadura não implementado",
    "Anão: Tradição de Heredrimm => Não implementado",
    "Dahllan: Empatia Selvagem => Não implementado",
    "Goblin: Engenhoso => Bônus em ofício ainda não implementado",
    "Lefou: Cria da Tormenta => Não implementado",
    "Minotauro: Chifres => Não implementado",
    "Golem: Chassi => Redução de Velocidade por Armadura e Excesso de Carga não implementados. Itens vestidos ainda não implementados",
    "Golem: Criatura Artifical => Imunidades não implementadas",
    "Golem: Propósito de Criação => Lista de poderes gerais ainda não implementada",
    "Golem: Fonte Elemental => Escolha da fonte implementada, mas imunidades e curas não",
    "Hynne: Arremessador => Não implementado",
    "Hynne: Pequeno e Rechonchudo => Atletismo com destreza ainda não implementado",
    "Hynne: Sorte Salvadora => Não implementado",
    "Kliren: Engenhosidade => Não implementado",
    "Kliren: Ossos Frágeis => Não implementado",
    "Kliren: Vanguardista => Não implementado",
    "Medusa: Natureza Venenosa => Não implementado",
    "Medusa: Olhar Atordoante => Não implementado",
    "Osteon: Armadura Óssea => Não implementado",
    "Osteon: Memória Póstuma => Tamanho da raça não implementado",
    "Osteon: Natureza Esquelética => Não implementado",
    "Osteon: Preço da Não-Vida => Não implementado",
    "Sereia/Tritão: Mestre do Tridente => Não implementado",
    "Sereia/Tritão: Transformação Anfíbia => Não implementado",
    "Sílfide: Asas de Borboleta => Não implementado",
    "Trog: Mal Cheiro => Não implementado",
    "Trog: Mordida => Não implementado",
    "Trog: Reptiliano => Bônus em furtividade não implementado",
    "Trog: Sangue Frio => Não implementado",
    "Com isso, a maioria das habilidades de raça está ativa e funcional. As próximas etapas envolverão a implementação das habilidades e poderes gerais de biografia.",
  ]),
  new PatchNote(4, "v0.7.4", [
    "Adicionada seleção de perícias treinadas pela biografia (a seleção de poderes de biografia está disponível, mas apenas algumas estão implementadas para teste)",
    "Adicionada seleção de perícias treinadas pela raça (Humano, Kliren e Osteon)",
    "Adicionada seleção de Resistência Elemental do Qareen (bônus de resistência ainda não implementados)",
    "Adicionados bônus de perícia fixos de raça (bônus como +2 em Fortitude de Goblin estão implementados, mas o +5 do Lefou contra efeitos da Tormenta não está). Os bônus fixos escolhidos ainda não foram implementados, como a deformidade do Lefou",
    "Adicionado bônus na defesa para Minotauro, Golem e Trog",
    "Adicionada seleção de poder pela habilidade Versátil do Humano e Propósito de Criação do Golem, mas ainda não está implementada. A seleção é apenas para testes visuais",
    "Memória Póstuma de Osteon apenas seleciona perícia, poderes virão mais adiante",
  ]),
  new PatchNote(3, "v0.7.3", [
    "Adicionada lista de habilidades das biografias (bônus ainda não implementados)",
    "Adicionada seleção das habilidades das biografias",
  ]),
  new PatchNote(2, "v0.7.2", [
    "mudança na UI para adicionar link para o servidor Área de RPG (modelo atual sujeito a alterações quando iniciar a versão de update de UI)",
    "adicionado nome das habilidades de raça das raças do livro básico",
    "remoção temporária das habilidades de classe de nível 1 de arcanista e bárbaro (virão em breve)",
    "adicionado patch notes para usuários acompanharem evolução",
  ]),
  new PatchNote(1, "v0.7.1", [
    "calculo de PV pelas classes e pelos atributos",
    "calculo de PM pelas classes",
    "seleção de classes por nível",
    "seleção de raça",
    "seleção de origem",
    "seleção do nível do personagem",
    "calculo de pericias considerando metade do nível e atributo chave",
    "outros campos de personagem ainda não estão funcionais (como nome, XP e velocidade) [talvez considerar avisar quando o XP atingir um marco quando subir de nível?]",
    "importado compra de pontos",
  ]),
];
